# Generated by Django 4.0.6 on 2022-07-24 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citizen',
            name='id_user',
        ),
    ]
