# Generated by Django 4.0.6 on 2022-07-23 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_alter_citizen_direction_alter_citizen_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='cel_number',
            field=models.IntegerField(verbose_name='Teléfono Celular'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='tel_number',
            field=models.IntegerField(verbose_name='Teléfono Fijo'),
        ),
    ]
