# Generated by Django 4.0.6 on 2022-07-23 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_alter_citizen_cel_number_alter_citizen_tel_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='cel_number',
            field=models.IntegerField(unique=True, verbose_name='Teléfono Celular'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='direction',
            field=models.CharField(max_length=50, unique=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='tel_number',
            field=models.IntegerField(unique=True, verbose_name='Teléfono Fijo'),
        ),
        migrations.AlterField(
            model_name='city',
            name='city_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='state',
            name='indicative',
            field=models.IntegerField(unique=True, verbose_name='Indicativo'),
        ),
        migrations.AlterField(
            model_name='state',
            name='state_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Departamento'),
        ),
    ]
